import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const config = readFileSync(new URL('../arduino/main/src/robot_config.h', import.meta.url), 'utf8')
const safety = readFileSync(new URL('../arduino/main/src/core/safety.h', import.meta.url), 'utf8')
const main = readFileSync(new URL('../arduino/main/main.ino', import.meta.url), 'utf8')
const motors = readFileSync(new URL('../arduino/main/src/core/motors.cpp', import.meta.url), 'utf8')
const motorTest = readFileSync(new URL('../arduino/main/test.ino', import.meta.url), 'utf8')
const mqttConfigExample = readFileSync(new URL('../arduino/main/src/config.example.h', import.meta.url), 'utf8')
const legacyMoodcamPoses = readFileSync(new URL('../arduino/main/src/legacy_moodcam_pose_reference.h', import.meta.url), 'utf8')

function functionBody(source, name, nextName) {
  const start = source.indexOf(name)
  const end = source.indexOf(nextName, start + name.length)
  assert.notEqual(start, -1, `${name} no encontrado`)
  assert.notEqual(end, -1, `${nextName} no encontrado`)
  return source.slice(start, end)
}

test('configura el mapa Moodcam y los limites de calibracion', () => {
  assert.match(config, /#define CALIBRATION_MODE false/)
  assert.match(config, /#define FINAL_ARM_MODE true/)
  assert.match(config, /#define FINAL_ARM_EXPLICITLY_CONFIGURED true/)
  assert.match(config, /static_assert\(!CALIBRATION_MODE \|\| SAFE_TEST_MODE/)
  assert.match(config, /SERVO_BASE, "base", 26, true, -30, 180, 90, 0/)
  assert.match(config, /SERVO_SHOULDER, "shoulder", 25, true, 45, 170, 90, -45/)
  assert.match(config, /SERVO_ELBOW, "elbow", 33, true, 35, 150, 90, 0/)
  assert.match(config, /SERVO_WRIST, "wrist", 32, true, 0, 120, 90, 0/)
  assert.doesNotMatch(config, /SERVO_BRUSH|BRUSH_SERVO_CONFIG/)
  assert.match(config, /CALIBRATION_MIN_DURATION_MS = 200/)
  assert.match(config, /CALIBRATION_MAX_DURATION_MS = 5000/)
})

test('el sketch de prueba usa la misma referencia angular que el firmware activo', () => {
  assert.match(motorTest, /#include "src\/robot_config\.h"/)
  assert.match(motorTest, /int posBase\s+= BASE_SERVO_CONFIG\.homeAngle/)
  assert.match(motorTest, /OFFSET_SERVO_HOMBRO = 45/)
  assert.match(motorTest, /OFFSET_SERVO_CODO = -10/)
  assert.match(motorTest, /int posHombro = SHOULDER_SERVO_CONFIG\.homeAngle - OFFSET_SERVO_HOMBRO/)
  assert.match(motorTest, /int posCodo\s+= ELBOW_SERVO_CONFIG\.homeAngle - OFFSET_SERVO_CODO/)
  assert.match(motorTest, /posicionLimitada \+ offsetServo/)
  assert.match(motorTest, /ANGULO_MIN_HOMBRO - OFFSET_SERVO_HOMBRO/)
  assert.match(motorTest, /ANGULO_MIN_CODO - OFFSET_SERVO_CODO/)
  assert.match(motorTest, /int posMuneca = WRIST_SERVO_CONFIG\.homeAngle/)
  assert.doesNotMatch(motorTest, /invertirDireccion|anguloMax - posicionLimitada/)
})

test('el firmware activo aplica el offset fisico del hombro a cada escritura', () => {
  assert.match(motors, /logicalAngle \+ config\.outputOffset/)
  assert.match(motors, /writeServoAngle\(shoulderServo, SHOULDER_SERVO_CONFIG, pose\.shoulder\)/)
  assert.match(motors, /writeServoAngle\(\*joint->servo, \*joint->config, joint->commandedAngle\)/)
})

test('conserva las poses Moodcam validadas solo como referencia de migracion', () => {
  assert.match(legacyMoodcamPoses, /Solo como referencia/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_REST = \{90, 90, 90, 90\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_PAINT_YELLOW = \{172, 158, 73, 17\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_PAINT_RED = \{143, 158, 85, 30\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_PAINT_VIOLET = \{30, 158, 90, 30\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_PAINT_BLUE = \{0, 162, 82, 22\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_WATER = \{90, 150, 48, 5\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_WATER_SHAKE_REPETITIONS = 15/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_TOWEL = \{0, 150, 50, 0\}/)
  assert.match(legacyMoodcamPoses, /LEGACY_MOODCAM_TOWEL_TAP_REPETITIONS = 10/)
})

test('ejecuta las poses Moodcam para cargar, limpiar y secar el pincel', () => {
  assert.match(main, /bool loadMoodcamPaint\(const String& paintId, int speed\)/)
  assert.match(main, /constexpr int PAINTING_WRIST_ANGLE_DEG = 40/)
  assert.match(main, /constexpr int PAINT_LOAD_WRIST_ANGLE_DEG = 20/)
  assert.match(main, /pose = \{170, 156, 80, PAINT_LOAD_WRIST_ANGLE_DEG\}/)
  assert.match(main, /pose = \{140, 158, 90, PAINT_LOAD_WRIST_ANGLE_DEG\}/)
  assert.match(main, /pose = \{20, 158, 90, PAINT_LOAD_WRIST_ANGLE_DEG\}/)
  assert.match(main, /pose = \{0, 160, 80, PAINT_LOAD_WRIST_ANGLE_DEG\}/)
  assert.match(main, /const ServoPose waterPose = \{90, 150, 55, 5\}/)
  assert.match(main, /WATER_SHAKE_REPETITIONS = 7/)
  assert.match(main, /WATER_SHAKE_WRIST_AMPLITUDE_DEG = 5/)
  assert.match(main, /const ServoPose right = \{90, 150, 55, WATER_SHAKE_WRIST_AMPLITUDE_DEG\}/)
  assert.match(main, /const ServoPose left = \{90, 150, 55, 0\}/)
  assert.match(main, /WATER_SHAKE_HALF_CYCLE_MS = 25/)
  assert.match(main, /DRY_TOWEL_REPETITIONS = 7/)
  assert.match(main, /DRY_TOWEL_HALF_CYCLE_MS = 20/)
  assert.match(main, /DRY_TOWEL_START_BASE_DEG = 0/)
  assert.match(main, /DRY_TOWEL_SWIPE_BASE_DEG = 30/)
  assert.match(main, /DRY_TOWEL_SHOULDER_DEG = 150/)
  assert.match(main, /DRY_TOWEL_ELBOW_DEG = 50/)
  assert.match(main, /DRY_TOWEL_WRIST_DEG = 0/)
  assert.match(main, /PAINT_LOAD_CIRCLE_REPETITIONS = 2/)
  assert.match(main, /PAINT_LOAD_CIRCLE_RADIUS_DEG = 5/)
  assert.match(main, /PAINT_LOAD_SETTLE_MS = 500/)
  assert.doesNotMatch(main, /createPaintLoadCommands/)
  const loadPaint = functionBody(main, 'bool loadMoodcamPaint(const String& paintId, int speed) {', 'bool rinseMoodcamBrush(int speed) {')
  assert.match(loadPaint, /activePaintId\.length\(\) > 0 && activePaintId != paintId[\s\S]*rinseMoodcamBrush\(speed\)[\s\S]*dryMoodcamBrush\(speed\)/)
  assert.match(loadPaint, /elbowBeforeShoulder \? moveToPaintHomeSafely\(\) : moveToHomeSlowly\(\)/)
  const execute = functionBody(main, 'bool executeRealPathCommand(const String& json, const String& type) {', 'bool moveMoodcamPose(')
  assert.match(execute, /if \(type == "stroke"\)[\s\S]*loadMoodcamPaint\(requestedPaintId/)
  assert.doesNotMatch(loadPaint, /paintShake|PAINT_SHAKE/)
  assert.match(main, /const ServoPose towelPose = \{[\s\S]*DRY_TOWEL_START_BASE_DEG,[\s\S]*DRY_TOWEL_SHOULDER_DEG,[\s\S]*DRY_TOWEL_ELBOW_DEG,[\s\S]*DRY_TOWEL_WRIST_DEG/)
  assert.match(main, /const ServoPose sweepPose = \{[\s\S]*DRY_TOWEL_SWIPE_BASE_DEG,[\s\S]*DRY_TOWEL_SHOULDER_DEG,[\s\S]*DRY_TOWEL_ELBOW_DEG,[\s\S]*DRY_TOWEL_WRIST_DEG/)
  assert.match(main, /for \(int repetition = 0; repetition < DRY_TOWEL_REPETITIONS; repetition\+\+\)/)
  assert.match(main, /moveMoodcamPose\(sweepPose, speed\)[\s\S]*waitSafely\(DRY_TOWEL_HALF_CYCLE_MS\)[\s\S]*moveMoodcamPose\(towelPose, speed\)[\s\S]*waitSafely\(DRY_TOWEL_HALF_CYCLE_MS\)/)
  assert.match(loadPaint, /const int paintLoadSpeed = constrain\(speed \/ 2, SAFE_MIN_SPEED, SAFE_MAX_SPEED\)/)
  assert.match(loadPaint, /paintPose\.shoulder,/)
  assert.match(loadPaint, /paintPose\.wrist/)
  assert.doesNotMatch(loadPaint, /paintPose\.shoulder \+ 1/)
  assert.match(loadPaint, /waitSafely\(PAINT_LOAD_SETTLE_MS\)/)
  assert.match(loadPaint, /for \(int repetition = 0; repetition < PAINT_LOAD_CIRCLE_REPETITIONS; repetition\+\+\)/)
  assert.match(loadPaint, /const ServoPose circlePoints\[\] = \{/)
  assert.doesNotMatch(main, /strokesSincePaintLoad/)
})

test('mapea los trazos a la zona angular segura basada en la pose roja', () => {
  const mapPoint = functionBody(main, 'ServoPose mapPointToPose(const PathPoint& point) {', 'void handleEmotionCommand(')
  assert.match(main, /PAINTING_BASE_MIN_DEG = 50/)
  assert.match(main, /PAINTING_BASE_MAX_DEG = 130/)
  assert.match(main, /PAINTING_SHOULDER_MIN_DEG = 167/)
  assert.match(main, /PAINTING_SHOULDER_MAX_DEG = 167/)
  assert.match(main, /PAINTING_ELBOW_MIN_DEG = 80/)
  assert.match(main, /PAINTING_ELBOW_MAX_DEG = 145/)
  assert.match(main, /PAINTING_WRIST_MIN_DEG = 20/)
  assert.match(main, /PAINTING_WRIST_MAX_DEG = 60/)
  assert.match(mapPoint, /const float verticalRatio = mapFloatRange\(/)
  assert.match(mapPoint, /const float horizontalRatio = mapFloatRange\(/)
  assert.match(mapPoint, /PAINTING_BASE_MIN_DEG, PAINTING_BASE_MAX_DEG/)
  assert.match(mapPoint, /PAINTING_SHOULDER_MIN_DEG, PAINTING_SHOULDER_MAX_DEG/)
  assert.match(mapPoint, /PAINTING_ELBOW_MAX_DEG, PAINTING_ELBOW_MIN_DEG/)
  assert.match(mapPoint, /PAINTING_WRIST_MIN_DEG,[\s\S]*PAINTING_WRIST_MAX_DEG/)
})

test('conserva las poses de las estaciones al limitar la zona de trazos', () => {
  assert.match(main, /pose = \{140, 158, 90, PAINT_LOAD_WRIST_ANGLE_DEG\}/)
  assert.match(main, /const ServoPose waterPose = \{90, 150, 55, 5\}/)
  assert.match(main, /DRY_TOWEL_START_BASE_DEG = 0/)
})

test('usa la pose calibrada del papel y fija la muneca a 40 grados durante todo el trazo', () => {
  const execute = functionBody(main, 'bool executeRealPathCommand(const String& json, const String& type) {', 'bool moveMoodcamPose(')
  assert.match(execute, /const bool strokePath = type == "stroke" && !profile\.forceBrushUp/)
  assert.match(execute, /const bool contactPoint = !profile\.forceBrushUp && \(profile\.forceBrushDown \|\| points\[index\]\.brush > 0\)/)
  assert.match(execute, /if \(strokePath\)/)
  assert.doesNotMatch(execute, /target\.shoulder \+ CANVAS_.*CONTACT_OFFSET_DEG/)
  assert.match(execute, /target\.wrist = PAINTING_WRIST_ANGLE_DEG/)
  assert.doesNotMatch(execute, /target\.elbow - CANVAS_.*CONTACT_OFFSET_DEG/)
})

test('pintura y toalla mueven base, codo, hombro y muneca', () => {
  const stationMove = functionBody(main, 'bool moveMoodcamStationPose(const ServoPose& target, int speed) {', 'bool moveToHomeSlowly()')
  assert.match(stationMove, /const ServoPose current = currentPose\(\)/)
  assert.match(stationMove, /const int stationSpeed = min\(speed, REAL_SPEED_PAINT_APPROACH\)/)
  assert.match(stationMove, /const ServoPose basePose = \{target\.base, current\.shoulder, current\.elbow, current\.wrist\}/)
  assert.match(stationMove, /const ServoPose elbowPose = \{target\.base, current\.shoulder, target\.elbow, current\.wrist\}/)
  assert.match(stationMove, /const ServoPose shoulderPose = \{target\.base, target\.shoulder, target\.elbow, current\.wrist\}/)
  assert.match(stationMove, /moveToPoseSafe\(basePose, stationSpeed\)[\s\S]*moveToPoseSafe\(elbowPose, stationSpeed\)[\s\S]*moveToPoseSafe\(shoulderPose, stationSpeed\)[\s\S]*moveToPoseSafe\(target, stationSpeed\)/)
  const loadPaint = functionBody(main, 'bool loadMoodcamPaint(const String& paintId, int speed) {', 'bool rinseMoodcamBrush(int speed) {')
  assert.match(loadPaint, /moveMoodcamPaintPose\(paintPose, elbowBeforeShoulder\)/)
  assert.match(main, /bool dryMoodcamBrush[\s\S]*moveMoodcamDryPose\(towelPose, speed\)/)
})

test('agua y secado realizan el 75 por ciento de la muneca antes de la pose final', () => {
  const waterMove = functionBody(main, 'bool moveMoodcamWaterPose(const ServoPose& target, int speed) {', 'bool moveToHomeSlowly()')
  assert.match(main, /REAL_SPEED_CLEANING = 40/)
  assert.match(waterMove, /ServoPose waterApproach = current/)
  assert.match(waterMove, /const int waterSpeed = min\(speed, REAL_SPEED_CLEANING\)/)
  assert.match(waterMove, /waterApproach\.base = target\.base;[\s\S]*waterApproach\.wrist = current\.wrist \+ \(target\.wrist - current\.wrist\) \* 3 \/ 4/)
  assert.match(waterMove, /waterApproach\.elbow = target\.elbow;[\s\S]*moveToPoseSafe\(waterApproach, waterSpeed\)/)
  assert.match(waterMove, /waterApproach\.shoulder = target\.shoulder;[\s\S]*moveToPoseSafe\(waterApproach, waterSpeed\)/)
  assert.match(waterMove, /waterApproach\.wrist = target\.wrist;[\s\S]*return moveToPoseSafe\(waterApproach, waterSpeed\)/)
  const rinse = functionBody(main, 'bool rinseMoodcamBrush(int speed) {', 'bool dryMoodcamBrush(int speed) {')
  assert.match(rinse, /moveMoodcamWaterPose\(waterPose, speed\)[\s\S]*for \(int repetition = 0; repetition < WATER_SHAKE_REPETITIONS; repetition\+\+\)/)
  assert.match(rinse, /const ServoPose right = \{90, 150, 55, WATER_SHAKE_WRIST_AMPLITUDE_DEG\}/)
  assert.match(rinse, /const ServoPose left = \{90, 150, 55, 0\}/)
  assert.match(rinse, /moveMoodcamPose\(waterPose, speed\) && moveWaterToHomeSafely\(\)/)
  const waterReturn = functionBody(main, 'bool moveWaterToHomeSafely() {', 'bool moodcamPaintPose(')
  assert.match(waterReturn, /const int approachWrist = current\.wrist \+ \(homePose\.wrist - current\.wrist\) \* 3 \/ 4/)
  assert.match(waterReturn, /shoulderPose = \{current\.base, homePose\.shoulder, current\.elbow, approachWrist\}/)
  assert.match(waterReturn, /elbowPose = \{current\.base, homePose\.shoulder, homePose\.elbow, approachWrist\}/)
  assert.match(waterReturn, /basePose = \{homePose\.base, homePose\.shoulder, homePose\.elbow, approachWrist\}/)
  assert.match(waterReturn, /moveToPoseSafe\(shoulderPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(elbowPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(basePose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(homePose, REAL_SPEED_PAINT_RETURN_HOME\)/)
  const dry = functionBody(main, 'bool dryMoodcamBrush(int speed) {', 'bool executeMoodcamStationCommand(')
  const dryMove = functionBody(main, 'bool moveMoodcamDryPose(const ServoPose& target, int speed) {', 'bool moveToHomeSlowly()')
  assert.match(dryMove, /const int drySpeed = min\(speed, REAL_SPEED_CLEANING\)/)
  assert.match(dryMove, /const int approachWrist = current\.wrist \+ \(target\.wrist - current\.wrist\) \* 3 \/ 4/)
  assert.match(dryMove, /basePose = \{target\.base, current\.shoulder, current\.elbow, approachWrist\}/)
  assert.match(dryMove, /moveToPoseSafe\(shoulderPose, drySpeed\)[\s\S]*moveToPoseSafe\(target, drySpeed\)/)
  assert.match(dry, /moveMoodcamDryPose\(towelPose, speed\) && moveDryToHomeSafely\(\)/)
})

test('carga color rapido servo por servo y vuelve rapido a HOME sin acelerar trazos', () => {
  const paintMove = functionBody(main, 'bool moveMoodcamPaintPose(const ServoPose& target, bool elbowBeforeShoulder) {', 'bool moveToHomeSlowly()')
  assert.match(main, /REAL_SPEED_STROKE_DEFAULT = 8/)
  assert.match(main, /REAL_SPEED_STROKE_MAX = 10/)
  assert.match(main, /FOUR_SERVO_CONTACT_SETTLE_MS = 250/)
  assert.match(main, /REAL_SPEED_PAINT_APPROACH = 40/)
  assert.match(main, /REAL_SPEED_PAINT_RETURN_HOME = 40/)
  assert.match(main, /PAINT_LOAD_SETTLE_MS = 500/)
  assert.match(main, /WATER_SHAKE_HALF_CYCLE_MS = 25/)
  assert.match(main, /DRY_TOWEL_HALF_CYCLE_MS = 20/)
  assert.match(paintMove, /basePose = \{target\.base, current\.shoulder, current\.elbow, current\.wrist\}/)
  assert.match(paintMove, /wristPose = \{target\.base, current\.shoulder, current\.elbow, target\.wrist\}/)
  assert.match(paintMove, /elbowPose = \{target\.base, current\.shoulder, target\.elbow, target\.wrist\}/)
  assert.match(paintMove, /shoulderPose = \{target\.base, target\.shoulder, current\.elbow, target\.wrist\}/)
  assert.match(paintMove, /if \(elbowBeforeShoulder\) \{[\s\S]*moveToPoseSafe\(basePose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(wristPose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(elbowPose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(target, REAL_SPEED_PAINT_APPROACH\)/)
  assert.match(paintMove, /moveToPoseSafe\(basePose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(wristPose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(shoulderPose, REAL_SPEED_PAINT_APPROACH\)[\s\S]*moveToPoseSafe\(target, REAL_SPEED_PAINT_APPROACH\)/)
  assert.match(main, /bool paintRequiresElbowBeforeShoulder\(const String& paintId\) \{[\s\S]*normalized == "yellow"[\s\S]*normalized == "amarillo"[\s\S]*normalized == "blue"[\s\S]*normalized == "light_blue"[\s\S]*normalized == "azul"/)
  assert.match(main, /moveMoodcamPaintPose\(paintPose, elbowBeforeShoulder\)/)
  const returnHome = functionBody(main, 'bool moveToHomeSlowly() {', 'bool moveToPaintHomeSafely()')
  assert.match(returnHome, /shoulderPose = \{current\.base, homePose\.shoulder, current\.elbow, current\.wrist\}/)
  assert.match(returnHome, /moveToPoseSafe\(shoulderPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(basePose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(wristPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(homePose, REAL_SPEED_PAINT_RETURN_HOME\)/)
  const paintHome = functionBody(main, 'bool moveToPaintHomeSafely() {', 'bool moodcamPaintPose(')
  assert.match(paintHome, /basePose = \{homePose\.base, current\.shoulder, current\.elbow, current\.wrist\}/)
  assert.match(paintHome, /wristPose = \{homePose\.base, current\.shoulder, current\.elbow, homePose\.wrist\}/)
  assert.match(paintHome, /elbowPose = \{homePose\.base, current\.shoulder, homePose\.elbow, homePose\.wrist\}/)
  assert.match(paintHome, /moveToPoseSafe\(basePose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(wristPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(elbowPose, REAL_SPEED_PAINT_RETURN_HOME\)[\s\S]*moveToPoseSafe\(homePose, REAL_SPEED_PAINT_RETURN_HOME\)/)
  const loadPaint = functionBody(main, 'bool loadMoodcamPaint(const String& paintId, int speed) {', 'bool rinseMoodcamBrush(int speed) {')
  assert.match(loadPaint, /const bool elbowBeforeShoulder = paintRequiresElbowBeforeShoulder\(paintId\)/)
  assert.match(loadPaint, /elbowBeforeShoulder \? moveToPaintHomeSafely\(\) : moveToHomeSlowly\(\)/)
})

test('arranca detached y con posicion desconocida sin asumir HOME fisico', () => {
  const begin = functionBody(motors, 'void beginMotors()', 'bool motorsConfigured()')
  assert.match(begin, /positionKnown = false/)
  assert.match(begin, /attached = false/)
  assert.ok(begin.indexOf('if (!FINAL_ARM_MODE)') < begin.indexOf('baseServo.attach'))

  const start = functionBody(motors, 'bool startCalibrationAssumingHome()', 'bool calibrationPositionKnown()')
  assert.doesNotMatch(start, /\.attach\(/)
  assert.doesNotMatch(start, /\.write\(/)
  assert.match(start, /positionKnown = true/)
})

test('parser admite enteros negativos y exige assume_home booleano', () => {
  assert.match(main, /json\.charAt\(valueEnd\) == '-'/)
  assert.match(main, /extractBoolValue\(json, "assume_home", false\)/)
  assert.match(main, /substring\(valueStart, valueStart \+ 4\) == "true"/)
})

test('jog y set_angle rechazan valores invalidos sin limitarlos', () => {
  assert.match(main, /delta == -5 \|\| delta == -1 \|\| delta == 1 \|\| delta == 5/)
  assert.match(main, /jog rechazado: el resultado supera los limites configurados/)
  assert.match(main, /set_angle rechazado: angulo fuera de limites/)
  assert.match(main, /duration_ms debe estar entre 200 y 5000/)
})

test('movimiento activo solo permite stop y get_joint_state', () => {
  assert.match(main, /calibrationMotionActive\(\) && type != "stop" && type != "get_joint_state" && type != "set_operating_mode"/)
  assert.match(main, /publishError\("robot_busy"\)/)
  assert.match(main, /!mqttClient\.connected\(\)[\s\S]*!calibrationMotionActive\(\)[\s\S]*connectMQTT\(\)/)
})

test('soporta cambio de modo operativo en runtime por MQTT', () => {
  assert.match(main, /"set_operating_mode"/)
  assert.match(main, /handleOperatingModeCommand\(json, fromMqtt\)/)
  assert.match(main, /operating_mode_changed/)
  assert.match(main, /operating_mode/)
  assert.match(main, /modeValue == "calibration"/)
  assert.match(main, /modeValue == "real"/)
})

test('STOP conserva attach y release detacha con posicion desconocida', () => {
  const stop = functionBody(motors, 'bool stopCalibrationMotion(', 'bool releaseCalibrationServos()')
  assert.doesNotMatch(stop, /\.detach\(/)
  assert.match(stop, /calibrationMotion\.active = false/)

  const release = functionBody(motors, 'bool releaseCalibrationServos()', 'JointCommandState calibrationJointState()')
  assert.match(release, /servo->detach\(\)/)
  assert.match(release, /positionKnown = false/)
  assert.match(main, /ADVERTENCIA: posible caida por gravedad/)
})

test('la interpolacion de calibracion es no bloqueante', () => {
  const update = functionBody(motors, 'bool updateCalibrationMotion(', 'bool stopCalibrationMotion(')
  assert.match(update, /millis\(\)/)
  assert.match(update, /commandedAngle \+= calibrationMotion\.direction/)
  assert.doesNotMatch(update, /delay\(/)
  assert.ok(main.indexOf('mqttClient.loop()') < main.indexOf('updateCalibrationMotion(completedServo'))
  assert.ok(main.indexOf('if (!Serial.available())') < main.indexOf('updateCalibrationMotion(completedServo'))
})

test('publica presencia MQTT periodica separada del estado del robot', () => {
  assert.match(mqttConfigExample, /#define TOPIC_ESP32_PRESENCE "system\/" MQTT_DEVICE_ID "\/presence\/esp32"/)
  assert.match(main, /constexpr unsigned long MQTT_PRESENCE_MS = 5000/)
  assert.match(main, /void publishPresence\(bool force\)/)
  assert.match(main, /mqttClient\.publish\(TOPIC_ESP32_PRESENCE, payload\.c_str\(\), true\)/)
  assert.match(main, /publishPresence\(true\)/)
  assert.match(main, /mqttClient\.loop\(\);[\s\S]*publishPresence\(\)/)
})

test('payload MQTT permite comandos largos con arrays de puntos', () => {
  assert.match(main, /constexpr size_t MAX_COMMAND_LENGTH = 2048/)
})

test('mapPointToPose usa la base limitada para el eje X del lienzo', () => {
  const body = functionBody(main, 'ServoPose mapPointToPose(const PathPoint& point) {', 'void handleEmotionCommand(const String& json, bool fromMqtt) {')
  assert.match(main, /PAINTING_BASE_MIN_DEG = 50/)
  assert.match(main, /PAINTING_BASE_MAX_DEG = 130/)
  assert.match(body, /verticalRatio = mapFloatRange\(/)
  assert.match(body, /horizontalRatio = mapFloatRange\(/)
  assert.match(body, /safeX,[\s\S]*PATH_MIN_X,[\s\S]*PATH_MAX_X/)
  assert.match(body, /horizontalRatio, 0\.0f, 1\.0f, PAINTING_BASE_MIN_DEG, PAINTING_BASE_MAX_DEG/)
  assert.match(body, /return \{[\s\S]*constrain\(static_cast<int>\(base\)/)
})

test('limita la zona de trazos sin ampliar limites mecanicos', () => {
  assert.match(main, /PAINTING_SHOULDER_MIN_DEG = 167/)
  assert.match(main, /PAINTING_SHOULDER_MAX_DEG = 167/)
  assert.match(main, /PAINTING_ELBOW_MIN_DEG = 80/)
  assert.match(main, /PAINTING_ELBOW_MAX_DEG = 145/)
  assert.match(main, /PAINTING_WRIST_MIN_DEG = 20/)
  assert.match(main, /PAINTING_WRIST_MAX_DEG = 60/)
  assert.match(main, /constrain\(static_cast<int>\(shoulder\), shoulderMin, shoulderMax\)/)
  assert.match(main, /constrain\(static_cast<int>\(elbow\), elbowMin, elbowMax\)/)
  assert.match(main, /constrain\(wrist, wristMin, wristMax\)/)
})

test('ServoPose incluye base y moveToPoseSafe interpola los cuatro servos', () => {
  const motorsHeader = readFileSync(new URL('../arduino/main/src/core/motors.h', import.meta.url), 'utf8')
  assert.match(motorsHeader, /struct ServoPose \{\s*int base;\s*int shoulder;\s*int elbow;\s*int wrist;\s*\}/)
  const move = functionBody(motors, 'bool moveToPoseSafe(const ServoPose& target, int speed) {', 'bool runPoseSequence(')
  assert.match(move, /constrain\(target\.base, BASE_SERVO_CONFIG\.minAngle, BASE_SERVO_CONFIG\.maxAngle\)/)
  assert.doesNotMatch(move, /if \(speed >= SAFE_MAX_SPEED\)/)
  assert.match(move, /abs\(safeTarget\.base - pose\.base\)/)
  assert.match(motors, /int degreesPerStepForSpeed\(int speed\)/)
  assert.match(motors, /SAFE_MIN_SPEED, SAFE_MAX_SPEED, 28, 8/)
  assert.match(motors, /SAFE_MIN_SPEED, SAFE_MAX_SPEED, 1, 4/)
  assert.match(move, /const int steps = max\(1, \(maxDelta \+ degreesPerStep - 1\) \/ degreesPerStep\)/)
  assert.match(move, /start\.base \+ \(\(safeTarget\.base - start\.base\) \* step\)/)
})

test('el cierre de cada chunk no limpia el pincel entre colores iguales', () => {
  const execute = functionBody(main, 'bool executeRealPathCommand(const String& json, const String& type) {', 'bool moveMoodcamPose(')
  assert.match(execute, /if \(type == "paint_sequence_end"\) \{\s*return true;/)
  assert.match(main, /bool moveToHomeSlowly\(\) \{[\s\S]*BASE_SERVO_CONFIG\.homeAngle/)
  assert.match(main, /moveToPoseSafe\(homePose, REAL_SPEED_PAINT_RETURN_HOME\)/)
  assert.match(main, /if \(type == "stroke" && !moveToHomeSlowly\(\)\)/)
})

test('moveToPoseSafe libera MQTT entre pasos via callback en lugar de delay bloqueante', () => {
  const motorsHeader = readFileSync(new URL('../arduino/main/src/core/motors.h', import.meta.url), 'utf8')
  assert.match(motorsHeader, /typedef void \(\*MotionTickCallback\)\(unsigned long durationMs\)/)
  assert.match(motorsHeader, /void setMotionTickCallback\(MotionTickCallback callback\)/)
  const move = functionBody(motors, 'bool moveToPoseSafe(const ServoPose& target, int speed) {', 'bool runPoseSequence(')
  assert.match(move, /waitWithMotionTick\(stepWaitMs\)/)
  assert.doesNotMatch(move, /delay\(stepDelayForSpeed/)
  assert.match(main, /setMotionTickCallback\(serviceMotionTick\)/)
  assert.match(main, /void serviceMotionTick\(unsigned long durationMs\)/)
  assert.match(main, /while \(millis\(\) - start < durationMs\)[\s\S]*mqttClient\.loop\(\)/)
})

test('al pasar a modo real sincroniza la pose interna con los angulos comandados', () => {
  const motorsHeader = readFileSync(new URL('../arduino/main/src/core/motors.h', import.meta.url), 'utf8')
  assert.match(motorsHeader, /void syncPoseToCommandedAngles\(\)/)
  assert.match(motors, /void syncPoseToCommandedAngles\(\) \{[\s\S]*baseJoint\.commandedAngle/)
  const handler = functionBody(main, 'void handleOperatingModeCommand(const String& json, bool fromMqtt) {', 'void handleCalibrationCommand(const String& json, const String& type) {')
  assert.match(handler, /if \(!isCalibrationMode\(\)\) \{\s*syncPoseToCommandedAngles\(\);/)
})

test('aplica protecciones especificas para el servo SG90 de la muneca y el codo extendido', () => {
  assert.match(safety, /SAFE_MAX_SPEED = 50/)
  assert.match(main, /REAL_SPEED_STROKE_DEFAULT = 8/)
  assert.match(main, /REAL_SPEED_CONTACT_DEFAULT = 50/)
  assert.match(main, /REAL_SPEED_TRANSIT_DEFAULT = 50/)
  assert.match(main, /REAL_SPEED_HOME_DEFAULT = 45/)
  assert.match(main, /WRIST_REAL_MAX_SPEED = 50/)
  assert.match(main, /WRIST_SIGNIFICANT_DELTA_DEG = 5/)
  assert.match(main, /ELBOW_EXTENSION_THRESHOLD_DEG = 110/)
  assert.match(main, /ELBOW_EXTENSION_SPEED_PENALTY = 3/)
  const execute = functionBody(main, 'bool executeRealPathCommand(const String& json, const String& type) {', 'RealCommandProfile buildRealCommandProfile(const String& type, const String& json) {')
  assert.match(execute, /abs\(target\.wrist - previousPose\.wrist\) > WRIST_SIGNIFICANT_DELTA_DEG/)
  assert.match(execute, /dynamicSpeed = min\(dynamicSpeed, WRIST_REAL_MAX_SPEED\)/)
  assert.match(execute, /target\.elbow > ELBOW_EXTENSION_THRESHOLD_DEG/)
  assert.match(execute, /dynamicSpeed - ELBOW_EXTENSION_SPEED_PENALTY/)
  assert.doesNotMatch(execute, /hasBrushServo|brushConfigured|setBrushPressureSafe/)
  assert.match(execute, /ServoPose target = mapPointToPose\(points\[index\]\)/)
  assert.match(execute, /FOUR_SERVO_CONTACT_SETTLE_MS/)
  assert.doesNotMatch(execute, /brush_not_configured/)
})

test('conserva el color entre chunks y carga pintura antes de cada trazo', () => {
  const queueStart = main.indexOf('void serviceRealCommandQueue() {')
  const queueEnd = main.indexOf('void printServoConfig(', queueStart)
  assert.notEqual(queueStart, -1, 'implementacion de serviceRealCommandQueue no encontrada')
  assert.notEqual(queueEnd, -1, 'fin de serviceRealCommandQueue no encontrado')
  const queue = main.slice(queueStart, queueEnd)
  assert.doesNotMatch(queue, /execution=ack/)
  assert.match(queue, /executeRealPathCommand\(command\.json, command\.type\)/)
  assert.match(queue, /real_command_failed/)

  const execute = functionBody(main, 'bool executeRealPathCommand(const String& json, const String& type) {', 'bool moveMoodcamPose(')
  assert.match(execute, /if \(type == "paint_sequence_start"\) \{\s*return true;/)
  assert.match(execute, /if \(type == "paint_sequence_end"\) \{\s*return true;/)
  assert.match(execute, /requestedPaintId\.length\(\) > 0[\s\S]*loadMoodcamPaint\(requestedPaintId/)
  const loadPaint = functionBody(main, 'bool loadMoodcamPaint(const String& paintId, int speed) {', 'bool rinseMoodcamBrush(int speed) {')
  assert.match(loadPaint, /activePaintId\.length\(\) > 0 && activePaintId != paintId/)
  assert.match(loadPaint, /rinseMoodcamBrush\(speed\)[\s\S]*dryMoodcamBrush\(speed\)/)
})

test('modo real usa FIFO acotado y publica backpressure para el AI Bridge', () => {
  assert.match(main, /constexpr size_t REAL_COMMAND_QUEUE_CAPACITY = 32/)
  assert.match(main, /struct QueuedRealCommand/)
  assert.match(main, /QueuedRealCommand realCommandQueue\[REAL_COMMAND_QUEUE_CAPACITY\]/)
  assert.match(main, /bool enqueueRealCommand\(const String& json, const String& type\)/)
  assert.match(main, /void serviceRealCommandQueue\(\)/)
  assert.match(main, /void clearRealCommandQueue\(\)/)
  assert.match(main, /publishQueueStatus\("queue_full"/)
  assert.match(main, /\\"queue_depth\\":/)
  assert.match(main, /\\"queue_full\\":/)
  assert.match(main, /clearRealCommandQueue\(\)[\s\S]*publishStopped/)
  assert.match(main, /mqttClient\.loop\(\);[\s\S]*publishPresence\(\);[\s\S]*serviceRealCommandQueue\(\)/)
})
